import argparse
import random

# TODO: put this in readable file
emotions = [
    "Fearful",
    "Angry",
    "Disgusted",
    "Sad",
    "Happy",
    "Surprised",
    "Busy",
    "Stressed",
    "Scared",
    "Anxious",
    "Insecure",
    "Weak",
    "Rejected",
    "Threatened",
    "Let Down",
    "Humiliated"
    "Bitter",
    "Mad",
    "Aggressive",
    "Frustrated",
    "Distant",
    "Critical",
    "Dissaproving",
    "Disappointed",
    "Awful",
    "Repelled",
    "Hurt",
    "Depressed",
    "Guilty",
    "Despair",
    "Vulnerable",
    "Lonely",
    "Optimistic",
    "Trusting",
    "Peaceful",
    "Powerful",
    "Accepted",
    "Proud",
    "Interested",
    "Content",
    "Playful",
    "xcited",
    "Amazed",
    "Confused",
    "Startled",
    "Out Of Control",
    "Overwhelmed",
    "Rushed",
    "Pressured",
    "Apathetic",
    "Indifferent",
    "Helpless",
    "Frightened",
    "Overwhelmed",
    "Worried",
    "Inadequate",
    "Inferior",
    "Worthless",
    "Insignificant",
    "Excluded",
    "Persecuted",
    "Nervous",
    "Exposed",
    "Betrayed",
    "Resentful",
    "Disrespected",
    "Ridiculed",
    "Indignant",
    "Violated",
    "Furious",
    "Jealous",
    "Provoked",
    "Hostile",
    "Infuriated",
    "Annoyed",
    "Withdrawn",
    "Numb",
    "Skeptical",
    "Dismissive",
    "Judgmental",
    "Embarrassed",
    "Appalled",
    "Revolted",
    "Nauseated",
    "Detesable",
    "Horrified",
    "Hesitant",
    "Dissapointed",
    "Inferior",
    "Empty",
    "Remorseful",
    "Ashamed",
    "Powerless",
    "Grief",
    "Fragile",
    "Victimized",
    "Abandoned",
    "Isolated",
    "Inspired",
    "Hopeful",
    "Intimate",
    "Sensitive",
    "Thankful",
    "Loving",
    "Creative",
    "Courageous",
    "Valued",
    "Respected",
    "Confident",
    "Successful",
    "Inquisitive",
    "Curious",
    "Joyful",
    "Free",
    "Cheeky",
    "Aroused",
    "Energetic",
    "Eager",
    "Awed",
    "Astonished",
    "Perplexed",
    "Disilliusioned",
    "Dismayed",
    "Shocked",
]

detailed = {
    'Bad': [
        "Bored",
        "Busy",
        "Stressed",
        "Out Of Control",
        "Overwhelmed",
        "Rushed",
        "Pressured",
        "Apathetic",
        "Indifferent",
    ]
}

if __name__ == "__main__":
    # TODO: Fix parser
    parser = argparse.ArgumentParser(description='Generate Random Emotions')
    parser.add_argument('count', metavar='N', type=int, nargs='+',
                        help='Number of ')
    print(random.choice(emotions))
